//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharePoint.SpecFlow.Tests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class TestsSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static TestsSettings defaultInstance = ((TestsSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TestsSettings())));
        
        public static TestsSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://rp2010-2:113")]
        public string SiteCollectionUrl {
            get {
                return ((string)(this["SiteCollectionUrl"]));
            }
            set {
                this["SiteCollectionUrl"] = value;
            }
        }
    }
}
